version: '2'
services:
    avaliacao360felipe-app:
        image: avaliacao360felipe
        external_links:
            - avaliacao360felipe-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/avaliacao360felipe
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    avaliacao360felipe-postgresql:
        extends:
            file: postgresql.yml
            service: avaliacao360felipe-postgresql
